//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebForms.hicmah {
	
	
	public partial class Installer3 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Button CreateSampleData;
		
		protected System.Web.UI.WebControls.Button CreateIndexes;
		
		protected System.Web.UI.WebControls.Button ProcessDimensions;
		
		protected System.Web.UI.WebControls.Button CacheQueries;
		
		protected System.Web.UI.WebControls.Button ClearCache;
		
		protected System.Web.UI.WebControls.Button DropIndexes;
		
		protected System.Web.UI.WebControls.Label Results;
	}
}
