//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukadc.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ukadc.Diagnostics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is invalid to specify both a propertyToken (&apos;{0}&apos;) and a dataProperty element on a &apos;{1}&apos;..
        /// </summary>
        internal static string BothPropertyTokenAndDataPropertyDefined {
            get {
                return ResourceManager.GetString("BothPropertyTokenAndDataPropertyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cleanInterval attribute must be a valid TimeSpan greater than Zero. The value &apos;{0}&apos; is invalid. Using default cleanInterval &apos;{1}&apos;..
        /// </summary>
        internal static string CleanIntervalCannotBeZero {
            get {
                return ResourceManager.GetString("CleanIntervalCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cleanInterval attribute must be a valid TimeSpan. The value &apos;{0}&apos; is invalid. Using default cleanInterval &apos;{1}&apos;..
        /// </summary>
        internal static string CleanIntervalInvalid {
            get {
                return ResourceManager.GetString("CleanIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CouldNotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default constructor could not be found on type &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindEmptyConstructor {
            get {
                return ResourceManager.GetString("CouldNotFindEmptyConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is of type &apos;{1}&apos; which does not implement IComparable or IConvertible and therefore cannot be evaluated or compared against..
        /// </summary>
        internal static string DoesNotImplementRightInterfaces {
            get {
                return ResourceManager.GetString("DoesNotImplementRightInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type &apos;{0}&apos; does not inherit from &apos;{1}&apos;..
        /// </summary>
        internal static string InheritanceError {
            get {
                return ResourceManager.GetString("InheritanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiFilter configuration error: No filterGroup with the name &apos;{0}&apos; could be found..
        /// </summary>
        internal static string MultiFilterGroupError {
            get {
                return ResourceManager.GetString("MultiFilterGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiFilter configuration error: filterGroup must contain at least 1 or more filters..
        /// </summary>
        internal static string MultiFilterMustContainOneFilter {
            get {
                return ResourceManager.GetString("MultiFilterMustContainOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; configuration section was found (&lt;section name=&apos;{0}&apos; type=&apos;{1}&apos; /&gt;)..
        /// </summary>
        internal static string NoConfigurationSectionFound {
            get {
                return ResourceManager.GetString("NoConfigurationSectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All single parameter constructors on the type &apos;{0}&apos; were tried but none could use the parameter &apos;{1}&apos; passed in..
        /// </summary>
        internal static string NoConstructorFound {
            get {
                return ResourceManager.GetString("NoConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a field or property called {0} on type {1} or it cannot be read.
        /// </summary>
        internal static string NoPropOrFieldOrInaccessible {
            get {
                return ResourceManager.GetString("NoPropOrFieldOrInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastPropertyGetter: There is no readable property &apos;{0}&apos; on type &apos;{1}&apos;..
        /// </summary>
        internal static string NoReadableProperty {
            get {
                return ResourceManager.GetString("NoReadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type &apos;{0}&apos; does not inherit or derive from the &apos;{1}&apos; type..
        /// </summary>
        internal static string NotAssignableFrom {
            get {
                return ResourceManager.GetString("NotAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation &apos;{0}&apos; is not supported by the &apos;{1}&apos;. Try one of the following operations &apos;{2}&apos;..
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyFilter configuration error: No propertyFilter with the name &apos;{0}&apos; could be found..
        /// </summary>
        internal static string PropertyFilterNotFound {
            get {
                return ResourceManager.GetString("PropertyFilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmtpTraceListener configuration error: No section with the name &apos;{0}&apos; could be found..
        /// </summary>
        internal static string SmtpTraceListenerConfigError {
            get {
                return ResourceManager.GetString("SmtpTraceListenerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlTraceListener configuration error: No section with the name &apos;{0}&apos; could be found..
        /// </summary>
        internal static string SqlTraceListenerConfigError {
            get {
                return ResourceManager.GetString("SqlTraceListenerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; already exists in the token dictionary and cannot be added..
        /// </summary>
        internal static string TokenAlreadyExists {
            get {
                return ResourceManager.GetString("TokenAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only specify one of format, type and dynamicProperty on a token element (token name=&apos;{0}&apos;)..
        /// </summary>
        internal static string TokenElementIncorrect {
            get {
                return ResourceManager.GetString("TokenElementIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has already been registered with the locator..
        /// </summary>
        internal static string TypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("TypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type &apos;{0}&apos; does not implement IComparable and cannot be used by the &apos;{1}&apos;..
        /// </summary>
        internal static string TypeDoesNotImplementIComparable {
            get {
                return ResourceManager.GetString("TypeDoesNotImplementIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has not been registered with this locator..
        /// </summary>
        internal static string TypeNotRegistered {
            get {
                return ResourceManager.GetString("TypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; does not exist in the token dictionary..
        /// </summary>
        internal static string UnrecognizedToken {
            get {
                return ResourceManager.GetString("UnrecognizedToken", resourceCulture);
            }
        }
    }
}
